import { describe, expect, it } from "vitest";
import type { PbMovement } from "../../types/pb";
import { planExcludeTransferMovementOps } from "./excludeTransfer";

const baseEvent = {
  excelRow: 10,
  movementNumber: "5",
  type: "ПРИБУВ",
  personId: "100",
  fullName: "Тестов Т.",
  rank: "солдат",
  previousIndex: "",
  nextIndex: "2103001",
  destination: "",
  orderNumber: "",
  orderDate: "",
  basisNumber: "",
  basisDate: "",
  changeText: "",
  status: "",
  note: "",
  arrivedFrom: "",
} satisfies PbMovement;

describe("disposition / exclude movement handlers", () => {
  it("planExcludeTransferMovementOps skips non-outbound events", () => {
    const result = planExcludeTransferMovementOps({
      event: baseEvent,
      existingOps: [],
      absenceOnlyBlocksExclusion: () => false,
      archiveAll: [],
      arrivalOf: () => null,
      byPersonName: () => null,
      cancelledExternalTransferRows: new Set(),
      createMovementKey: () => "",
      dayByIndex: new Map(),
      ejoosShpo: [],
      excludedTimesheetWrite: () => ({
        createHistory: false,
        replaceInPlace: false,
        sourceExcelRow: 0,
      }),
      externalTransferProcessState: () => "pending",
      extractTimesheetDestinationFromPosition: () => "",
      findMovementExcludedRow: () => null,
      formatTransferDestinationForTimesheet: () => "",
      inboundStaffDateFor: () => "",
      inboundStaffPlacementBefore: () => null,
      internalPositionMovementRows: new Set(),
      isOutboundStaffMove: () => false,
      isOwnFirstPbDestination: () => false,
      isPositionChangeRow: () => false,
      isPositionIndex: () => true,
      isSamePerson: () => false,
      isUnrecordedSameMonthTransit: () => false,
      isVacantStaffRow: () => false,
      latestRankEventByPerson: new Map(),
      movementEventTime: () => 0,
      movementPersonKey: () => "",
      onStaffOos: () => false,
      onStaffShpo: () => false,
      oosPersonById: new Map(),
      oosPersonByName: new Map(),
      openDispositionAbsenceMs: () => 0,
      opId: (...parts) => parts.join(":"),
      parseRankPromotion: () => ({ previousRank: "", nextRank: "" }),
      pendingRankByPerson: new Map(),
      personIdFromShpo: () => "",
      personStillInEjoos: () => false,
      personStillInSh: () => false,
      positionChangeDestination: () => "",
      shpoByIndex: new Map(),
      skipExternalIfAlreadyProcessed: () => false,
      sourcePositionTitleForOutbound: () => "",
      staffEpisodePaintPayload: () => ({
        timesheetActiveFrom: "",
        timesheetPreserveHistory: "",
        timesheetAbsenceSpans: "",
        historyTimesheetExcelRow: "",
        historyTimesheetAbsenceSpans: "",
      }),
      staleExcludedForMovement: () => [],
      staleExcludedClearPayload: () => ({}),
      timesheetClosedFor: () => false,
      timesheetRowInExpectedUnitSection: () => true,
      timesheetRowsOf: () => [],
      timesheetSheet: undefined,
      transferCancelOf: () => null,
      unitCodeFromMovement: () => "",
      wasMovementProcessed: () => false,
      laterReturnSupersedesOutbound: () => false,
    });
    expect(result.handled).toBe(false);
    expect(result.ops).toHaveLength(0);
  });
});
